### ISSUE TITLE
Datetime fields not staying popped up

### ISSUE THREAD

**Issue by nbb** [icelab/roneo#6]
![datetime_problem](https://cloud.githubusercontent.com/assets/911611/16034136/642c92b0-3253-11e6-8f72-a5c7d725e0bc.gif)

**Comment by makenosound** [comment]
This is an issue in https://github.com/icelab/formalist-standard-react/issues/28.

**Comment by makenosound** [comment]
Fixed in https://github.com/icelab/formalist-standard-react/commit/0efeb8606b61a39f2e22f624f3e6efd18e4ba4db
